import { useEffect, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Mail, Search, Plus, RefreshCw, X, Paperclip } from 'lucide-react'
import Layout from '../components/Layout'
import { Button, Input, Select, Spinner, Badge, Modal } from '../components/ui'
import api, { state } from '../lib/api'
import { fmtTime } from '../lib/utils'

const emptyFilters = { query: '', domain: '', address: '', sender: '', unread: '', has_mail: '', has_attachment: '', sort_by: 'created_at', sort_order: 'desc' }

export default function WorkspacePage() {
  const admin = !!state.isAdmin
  const [view, setView] = useState('addresses')
  const [filters, setFilters] = useState(emptyFilters)
  const [selected, setSelected] = useState(null)
  const [showCreate, setShowCreate] = useState(false)
  const [credentialAddress, setCredentialAddress] = useState(null)
  const [page, setPage] = useState(0)
  const pageSize = 100
  const qc = useQueryClient()
  const update = (k, v) => setFilters(x => ({ ...x, [k]: v }))
  const addressQ = useQuery({ queryKey: ['workspace-addresses', admin, filters, page], queryFn: async () => {
    if (!admin) return (await api('/user_api/dashboard')).data
    const p = new URLSearchParams({ limit: String(pageSize), offset: String(page * pageSize), query: filters.query, domain: filters.domain, unread: filters.unread, has_mail: filters.has_mail, sort_by: filters.sort_by, sort_order: filters.sort_order })
    return (await api(`/admin/address?${p}`)).data
  } })
  const mailQ = useQuery({ queryKey: ['workspace-mails', admin, filters, page], enabled: view === 'mails', queryFn: async () => {
    const p = new URLSearchParams({ limit: String(pageSize), offset: String(page * pageSize), address: filters.address, domain: filters.domain, sender: filters.sender, query: filters.query, unread: filters.unread, has_attachment: filters.has_attachment, sort_by: filters.sort_by === 'created_at' ? 'created_at' : 'id', sort_order: filters.sort_order })
    return (await api(`${admin ? '/admin/workspace_mails' : '/user_api/workspace_mails'}?${p}`)).data
  } })
  const addressRows = (addressQ.data?.results || []).filter(a => !filters.query || String(a.name || '').toLowerCase().includes(filters.query.toLowerCase())).filter(a => !filters.domain || String(a.name || '').toLowerCase().endsWith('@' + filters.domain.toLowerCase()))
  const settingsQ = useQuery({ queryKey: ['workspace-domains'], queryFn: () => api('/open_api/settings').then(r => r.data) })
  const usageQ = useQuery({ queryKey: ['user-usage'], enabled: !admin, queryFn: () => api('/user_api/usage').then(r => r.data) })
  const domains = (admin ? settingsQ.data?.domains : settingsQ.data?.defaultDomains) || settingsQ.data?.domains || []
  const allRows = view === 'addresses' ? addressRows : (mailQ.data?.results || [])
  const rows = !admin && view === 'addresses' ? allRows.slice(page * pageSize, (page + 1) * pageSize) : allRows
  const count = view === 'addresses' ? (admin ? (addressQ.data?.count || 0) : allRows.length) : (mailQ.data?.count || 0)
  const lastPage = Math.max(0, Math.ceil(count / pageSize) - 1)
  const change = (k, v) => { update(k, v); setPage(0) }
  const switchView = v => { setView(v); setPage(0) }
  const openAddress = (a) => { setFilters(x => ({ ...x, address: a.name })); switchView('mails') }
  const openMail = async (m) => { const r = await api(`${admin ? '/admin/workspace_mail/' : '/user_api/workspace_mail/'}${m.id}`); if (r.status === 200) setSelected(r.data) }
  const loading = addressQ.isLoading || (view === 'mails' && mailQ.isLoading)
  return <Layout><div className="mx-auto max-w-[1500px] px-4 py-5 sm:px-6">
    <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">邮箱与邮件</h1><p className="mt-1 text-sm text-muted-foreground">{admin ? '管理员视图 · 全部邮箱和邮件' : '你的邮箱和邮件'}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => { addressQ.refetch(); mailQ.refetch() }}><RefreshCw className="h-4 w-4" />刷新</Button><Button size="sm" onClick={() => setShowCreate(true)}><Plus className="h-4 w-4" />新建邮箱</Button></div></div>
    <div className="mb-4 flex flex-wrap items-center gap-2 border-b border-border pb-3"><div className="flex rounded-md bg-muted p-1"><button className={`px-3 py-1.5 text-sm ${view === 'addresses' ? 'rounded bg-background font-medium shadow-sm' : 'text-muted-foreground'}`} onClick={() => switchView('addresses')}>邮箱</button><button className={`px-3 py-1.5 text-sm ${view === 'mails' ? 'rounded bg-background font-medium shadow-sm' : 'text-muted-foreground'}`} onClick={() => switchView('mails')}>邮件</button></div><div className="flex min-w-[220px] flex-1 items-center gap-2 rounded-md border border-input bg-background px-3"><Search className="h-4 w-4 text-muted-foreground" /><Input className="border-0 px-0 focus-visible:ring-0" placeholder={view === 'addresses' ? '搜索邮箱地址' : '搜索主题、正文、发件人'} value={filters.query} onChange={e => change('query', e.target.value)} /></div><Select value={filters.domain} onChange={e => change('domain', e.target.value)}><option value="">所有域名</option>{domains.map(d => <option key={d}>{d}</option>)}</Select><Select value={filters.unread} onChange={e => change('unread', e.target.value)}><option value="">全部状态</option><option value="1">仅未读</option></Select>{view === 'addresses' ? <Select value={filters.has_mail} onChange={e => change('has_mail', e.target.value)}><option value="">全部邮箱</option><option value="1">有邮件</option></Select> : <Select value={filters.has_attachment} onChange={e => change('has_attachment', e.target.value)}><option value="">全部邮件</option><option value="1">有附件</option></Select>}<Select value={filters.sort_by} onChange={e => change('sort_by', e.target.value)}><option value="created_at">时间</option><option value="name">邮箱</option><option value="mail_count">邮件数</option><option value="id">ID</option></Select><button className="icon-button" title="切换排序" onClick={() => change('sort_order', filters.sort_order === 'desc' ? 'asc' : 'desc')}>{filters.sort_order === 'desc' ? '↓' : '↑'}</button>{(filters.query || filters.domain || filters.unread || filters.address || filters.has_mail || filters.has_attachment) && <Button size="sm" variant="ghost" onClick={() => { setFilters(emptyFilters); setPage(0) }}><X className="h-4 w-4" />清除</Button>}</div>
    {loading && <div className="flex justify-center p-16"><Spinner /></div>}
    {!loading && !admin && usageQ.data && <UsageSummary data={usageQ.data} />}
    {!loading && view === 'addresses' && <AddressTable rows={rows} onOpen={openAddress} admin={admin} onCredential={setCredentialAddress} onDelete={async (a) => { if (confirm(`删除邮箱 ${a.name}？`)) { const r = await api(`/user_api/address/${a.id}`, 'DELETE'); if (r.status === 200) { addressQ.refetch(); usageQ.refetch() } else alert(r.data || '删除失败') } }} />}
    {!loading && view === 'mails' && <MailTable rows={rows} onOpen={openMail} />}
    {!loading && <div className="mt-3 flex flex-wrap items-center justify-between gap-3 text-sm text-muted-foreground"><span>共 {count} 条 · 第 {count ? page + 1 : 0} / {count ? lastPage + 1 : 0} 页</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page <= 0} onClick={() => setPage(0)}>首页</Button><Button size="sm" variant="outline" disabled={page <= 0} onClick={() => setPage(x => x - 1)}>上一页</Button><Input aria-label="跳转页码" className="h-8 w-16 text-center" type="number" min="1" max={Math.max(1, lastPage + 1)} value={count ? page + 1 : ''} onChange={e => { const n = Number(e.target.value); if (n >= 1) setPage(Math.min(lastPage, n - 1)) }} /><Button size="sm" variant="outline" disabled={page >= lastPage} onClick={() => setPage(x => x + 1)}>下一页</Button><Button size="sm" variant="outline" disabled={page >= lastPage} onClick={() => setPage(lastPage)}>末页</Button></div></div>}
  </div>{showCreate && <CreateAddressWithCredential onClose={() => { setShowCreate(false); qc.invalidateQueries({ queryKey: ['workspace-addresses'] }) }} />}{credentialAddress && <CredentialModal address={credentialAddress} admin={admin} onClose={() => setCredentialAddress(null)} />}{selected && <MailDetail m={selected} admin={admin} onClose={() => setSelected(null)} onChanged={() => { setSelected(null); mailQ.refetch(); addressQ.refetch() }} />}</Layout>
}

function AddressTable({ rows, onOpen, onDelete, onCredential, admin }) { return <div className="overflow-x-auto rounded-lg border border-border bg-background"><table className="w-full text-sm"><thead className="bg-muted text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">邮箱</th>{admin && <th className="px-4 py-3">所有者</th>}<th className="px-4 py-3">邮件</th><th className="px-4 py-3">未读</th><th className="px-4 py-3">最近收信</th><th className="px-4 py-3">创建时间</th><th className="px-4 py-3" /></tr></thead><tbody>{rows.map(a => <tr key={a.id} className="border-t border-border hover:bg-accent"><td className="max-w-[320px] break-all px-4 py-3 font-medium">{a.name}</td>{admin && <td className="px-4 py-3 text-xs text-muted-foreground">{a.owner_emails || '未绑定'}</td>}<td className="px-4 py-3">{a.mail_count || 0}</td><td className="px-4 py-3">{a.unread_count || 0}</td><td className="px-4 py-3 text-xs text-muted-foreground">{a.last_mail_at ? fmtTime(a.last_mail_at) : '暂无'}</td><td className="px-4 py-3 text-xs text-muted-foreground">{fmtTime(a.created_at)}</td><td className="px-4 py-3"><div className="flex gap-1"><Button size="sm" variant="outline" onClick={() => onOpen(a)}>查看邮件</Button><Button size="sm" variant="ghost" onClick={() => onCredential(a)}>凭据</Button>{!admin && <Button size="sm" variant="ghost" onClick={() => onDelete(a)}>删除</Button>}</div></td></tr>)}{!rows.length && <tr><td colSpan={admin ? 7 : 6} className="px-4 py-12 text-center text-muted-foreground">暂无邮箱</td></tr>}</tbody></table></div> }

function CredentialModal({ address, admin, onClose }) { const [token, setToken] = useState(''); const [error, setError] = useState(''); useEffect(() => { let active = true; const path = admin ? `/admin/show_password/${address.id}` : `/user_api/bind_address_jwt/${address.id}`; api(path).then(r => { if (!active) return; if (r.status === 200 && r.data?.jwt) setToken(r.data.jwt); else setError(typeof r.data === 'string' ? r.data : '凭据加载失败') }).catch(() => active && setError('凭据加载失败')); return () => { active = false } }, [address.id, admin]); return <Modal title={`邮箱凭据 · ${address.name}`} onClose={onClose}><div className="space-y-3"><p className="text-sm text-muted-foreground">这是访问该邮箱 API 的 Address JWT，不是用户登录密码。</p><div className="max-h-48 min-h-16 overflow-auto break-all rounded-md border border-border p-3 font-mono text-xs">{error || token || '加载中…'}</div><Button className="w-full" disabled={!token} onClick={() => { navigator.clipboard?.writeText(token); alert('已复制凭据') }}>复制凭据</Button></div></Modal> }
function MailTable({ rows, onOpen }) { return <div className="overflow-x-auto rounded-lg border border-border bg-background"><table className="w-full text-sm"><thead className="bg-muted text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">主题</th><th className="px-4 py-3">邮箱</th><th className="px-4 py-3">发件人</th><th className="px-4 py-3">时间</th><th className="px-4 py-3">状态</th></tr></thead><tbody>{rows.map(m => <tr key={m.id} onClick={() => onOpen(m)} className="cursor-pointer border-t border-border hover:bg-accent"><td className="max-w-[340px] px-4 py-3 font-medium">{m.subject || '(无主题)'}</td><td className="max-w-[260px] break-all px-4 py-3 text-xs">{m.address}</td><td className="max-w-[260px] break-all px-4 py-3 text-xs text-muted-foreground">{m.sender || m.source}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-muted-foreground">{fmtTime(m.created_at)}</td><td className="px-4 py-3">{m.is_unread ? <Badge variant="primary">未读</Badge> : <Badge variant="muted">已读</Badge>}</td></tr>)}{!rows.length && <tr><td colSpan="5" className="px-4 py-12 text-center text-muted-foreground">暂无邮件</td></tr>}</tbody></table></div> }
function MailDetail({ m, admin, onClose, onChanged }) {
  const [mode, setMode] = useState(m.html ? 'html' : 'text')
  const prefix = admin ? '/admin/workspace_mail/' : '/user_api/workspace_mail/'
  const srcDoc = `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data: cid:; style-src 'unsafe-inline'; font-src data:"><base target="_blank">${m.html || ''}`
  const saveRaw = () => { const url = URL.createObjectURL(new Blob([m.raw || ''], { type: 'message/rfc822' })); const a = document.createElement('a'); a.href = url; a.download = `mail-${m.id}.eml`; a.click(); URL.revokeObjectURL(url) }
  const mark = async () => { await api(`${prefix}${m.id}/read`, 'PATCH', { isUnread: !m.is_unread }); onChanged() }
  const del = async () => { if (confirm('删除这封邮件？')) { await api(`${prefix}${m.id}`, 'DELETE'); onChanged() } }
  return <Modal title={m.subject || '(无主题)'} onClose={onClose}><div className="space-y-3"><div className="text-xs text-muted-foreground">{m.sender} · {m.address} · {m.created_at}</div><div className="flex flex-wrap gap-1 border-b border-border pb-2">{m.html && <Button size="sm" variant={mode === 'html' ? 'default' : 'ghost'} onClick={() => setMode('html')}>HTML</Button>}<Button size="sm" variant={mode === 'text' ? 'default' : 'ghost'} onClick={() => setMode('text')}>纯文本</Button><Button size="sm" variant={mode === 'raw' ? 'default' : 'ghost'} onClick={() => setMode('raw')}>原始邮件</Button><div className="ml-auto flex gap-1"><Button size="sm" variant="outline" onClick={mark}>{m.is_unread ? '标为已读' : '标为未读'}</Button><Button size="sm" variant="outline" onClick={saveRaw}>下载 EML</Button><Button size="sm" variant="ghost" onClick={del}>删除</Button></div></div>{mode === 'html' && <iframe title="mail" sandbox="allow-popups" srcDoc={srcDoc} className="mail-frame" />}{mode === 'text' && <pre className="max-h-[55vh] overflow-auto whitespace-pre-wrap text-sm">{m.text || '无正文'}</pre>}{mode === 'raw' && <pre className="max-h-[55vh] overflow-auto whitespace-pre-wrap rounded-md bg-muted p-3 text-xs">{m.raw || '无原始邮件'}</pre>}{m.attachments?.length > 0 && <div className="border-t border-border pt-3 text-sm"><div className="mb-2 font-medium">附件</div>{m.attachments.map((a, i) => <div key={i} className="flex items-center gap-2 text-xs"><Paperclip className="h-3.5 w-3.5" />{a.filename} ({a.size} bytes)</div>)}</div>}</div></Modal>
}
function CreateAddress({ onClose }) { const [name, setName] = useState(''); const [domain, setDomain] = useState(''); const [err, setErr] = useState(''); const domainsQ = useQuery({ queryKey: ['open-domains'], queryFn: () => api('/open_api/domains').then(r => r.data) }); const domains = domainsQ.data?.domains || []; const submit = async () => { if (!domain || !domains.includes(domain)) { setErr('请选择有效域名'); return } const r = await api('/api/new_address', 'POST', { name, domain, cf_token: '' }); if (r.status === 200) onClose(); else setErr(typeof r.data === 'string' ? r.data : '创建失败') }; return <Modal title="新建邮箱" onClose={onClose}><div className="space-y-3"><Input placeholder="邮箱前缀（留空随机生成）" value={name} onChange={e => setName(e.target.value)} /><Select value={domain} onChange={e => setDomain(e.target.value)} disabled={domainsQ.isLoading || !domains.length}><option value="">选择域名</option>{domains.map(d => <option key={d} value={d}>{d}</option>)}</Select>{err && <p className="text-sm text-destructive">{err}</p>}<Button className="w-full" onClick={submit}><Plus className="h-4 w-4" />创建</Button></div></Modal> }

function UsageSummary({ data }) { const l = data.limits || {}; const u = data.used || {}; const monthly = u.monthly || {}; const value = (n) => n == null || n < 0 ? '无限' : n; return <div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['邮箱总数', `${u.address_count || 0} / ${value(l.max_address_count)}`], ['邮件总量', `${u.mail_count || 0} / ${value(l.max_mail_count)}`], ['本月创建邮箱', `${monthly.addresses_created || 0} / ${value(l.monthly_address_quota)}`], ['本月接收邮件', `${monthly.mails_received || 0} / ${value(l.monthly_receive_quota)}`]].map(([label, val]) => <div key={label} className="rounded-md border border-border bg-card px-4 py-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-lg font-semibold">{val}</div></div>)}<div className="text-xs text-muted-foreground sm:col-span-2 lg:col-span-4">发信权限：{l.can_send_mail ? '已开启' : '未开启'}</div></div> }

function CreateAddressWithCredential({ onClose }) { const [name, setName] = useState(''); const [domain, setDomain] = useState(''); const [err, setErr] = useState(''); const [res, setRes] = useState(null); const domainsQ = useQuery({ queryKey: ['open-domains'], queryFn: () => api('/open_api/domains').then(r => r.data) }); const domains = domainsQ.data?.domains || []; const submit = async () => { if (!domain || !domains.includes(domain)) { setErr('请选择有效域名'); return } const r = await api('/api/new_address', 'POST', { name, domain, cf_token: '' }); if (r.status === 200) setRes(r.data); else setErr(typeof r.data === 'string' ? r.data : '创建失败') }; return <Modal title="新建邮箱" onClose={onClose}>{res ? <div className="space-y-3"><div className="rounded-md border border-border p-3 text-sm"><div className="break-all font-medium">{res.address}</div><div className="mt-2 break-all text-xs text-muted-foreground">Address JWT：{res.jwt}</div></div><Button className="w-full" onClick={() => { navigator.clipboard?.writeText(res.jwt || ''); onClose() }}>复制凭据并关闭</Button></div> : <div className="space-y-3"><Input placeholder="邮箱前缀（留空随机生成）" value={name} onChange={e => setName(e.target.value)} /><Select value={domain} onChange={e => setDomain(e.target.value)} disabled={domainsQ.isLoading || !domains.length}><option value="">选择域名</option>{domains.map(d => <option key={d}>{d}</option>)}</Select>{err && <p className="text-sm text-destructive">{err}</p>}<Button className="w-full" onClick={submit}><Plus className="h-4 w-4" />创建</Button></div>}</Modal> }
